export const CURRENCY_FORMAT = {
  'CNY': '¥',
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'AUD': '$',
  'AED': '"dh"',
  'BRL': '"R$"',
  'CAD': '$',
  'CHF': '"CHF"',
  'HKD': '$',
  'INR': '₹',
  'JPY': '¥',
  'KRW': '₩',
  'MOP': '"MOP$"',
  'MXN': '$',
};

export const CURRENCY = [
  { name: 'CNY', value: 'CNY' },
  { name: 'USD', value: 'USD' },
  { name: 'EUR', value: 'EUR' },
  { name: 'GBP', value: 'GBP' },
  { name: 'AUD', value: 'AUD' },
  { name: 'AED', value: 'AED' },
  { name: 'BRL', value: 'BRL' },
  { name: 'CAD', value: 'CAD' },
  { name: 'CHF', value: 'CHF' },
  { name: 'HKD', value: 'HKD' },
  { name: 'INR', value: 'INR' },
  { name: 'JPY', value: 'JPY' },
  { name: 'KRW', value: 'KRW' },
  { name: 'MOP', value: 'MOP' },
  { name: 'MXN', value: 'MXN' },
];